import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Link from 'next/link';
import React, {useState} from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const requestFunds: NextPage = () => {

  const [formState, setFormState] = useState({
    estAmount: '',
    tradesNum: '',
    estROI: ''
  });

  const handleChange = (e) => {
    setFormState({
      ...formState,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Handle form submission here
    console.log(formState);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>PLUTO</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Request for a Funded Account
        </h1>

        <div className={styles.form}>
            <h2>Join Us!! </h2>
            <p>Apply!</p>
            <form onSubmit={handleSubmit}>
              <label htmlFor="estAmount">Estimated amount: </label>
              <input type="text" name="estAmount" value={formState.estAmount} onChange={handleChange} required />
              <br />
              <br />
              <label htmlFor="tradesNum">Number of trades: </label>
              <input type="text" name="tradesNum" value={formState.tradesNum} onChange={handleChange} required />
              <br />
              <br />
              <label htmlFor="estROI">Expected ROI: </label>
              <input type="text" name="estROI" value={formState.estROI} onChange={handleChange} required />
              <br />
              <br />
              <button type="submit">&rarr; Submit</button>
            </form>
          </div>
          
      </main>

      <footer className={styles.footer}>
      <Link href="/">
           Home
        </Link>
        <a href="_" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by 0xdeivid
        </a>
      </footer>
    </div>
  );
};

export default requestFunds;
